export const playlists = [
  {
    id: "1",
    title: "Chill Vibes",
    description: "Relaxing beats for your downtime",
    cover: "music.avif/?height=220&width=220&text=Chill+Vibes",
  },
  {
    id: "2",
    title: "Workout Mix",
    description: "High energy tracks to keep you moving",
    cover: "/music.avif?height=220&width=220&text=Workout+Mix",
  },
  {
    id: "3",
    title: "Focus Flow",
    description: "Ambient sounds for deep concentration",
    cover: "/music.avif?height=220&width=220&text=Focus+Flow",
  },
  {
    id: "4",
    title: "Throwback Hits",
    description: "Classic tracks from the past decades",
    cover: "/music.avif?height=220&width=220&text=Throwback+Hits",
  },
  {
    id: "5",
    title: "Indie Discoveries",
    description: "Fresh finds from independent artists",
    cover: "/music.avif?height=220&width=220&text=Indie+Discoveries",
  },
  {
    id: "6",
    title: "Electronic Pulse",
    description: "Cutting-edge electronic music",
    cover: "/music.avif?height=220&width=220&text=Electronic+Pulse",
  },
  {
    id: "7",
    title: "Morning Coffee",
    description: "Gentle tunes to start your day",
    cover: "/music.avif?height=220&width=220&text=Morning+Coffee",
  },
  {
    id: "8",
    title: "Late Night Drive",
    description: "Atmospheric tracks for night cruising",
    cover: "/music.avif?height=220&width=220&text=Late+Night+Drive",
  },
]

export const albums = [
  {
    id: "1",
    title: "Neon Dreams",
    artist: "Synthwave Collective",
    cover: "/photo.avif?height=200&width=200&text=Neon+Dreams",
  },
  {
    id: "2",
    title: "Midnight Echo",
    artist: "Luna Ray",
    cover: "/photo.avif?height=200&width=200&text=Midnight+Echo",
  },
  {
    id: "3",
    title: "Urban Pulse",
    artist: "Metro Beats",
    cover: "/photo.avif?height=200&width=200&text=Urban+Pulse",
  },
  {
    id: "4",
    title: "Ethereal Spaces",
    artist: "Ambient Architects",
    cover: "/photo.avif?height=200&width=200&text=Ethereal+Spaces",
  },
  {
    id: "5",
    title: "Digital Horizon",
    artist: "Cyber Collective",
    cover: "/photo.avif?height=200&width=200&text=Digital+Horizon",
  },
  {
    id: "6",
    title: "Neon Nights",
    artist: "Electric Dreams",
    cover: "/photo.avif?height=200&width=200&text=Neon+Nights",
  },
  {
    id: "7",
    title: "Future Nostalgia",
    artist: "Retro Wave",
    cover: "/photo.avif?height=200&width=200&text=Future+Nostalgia",
  },
  {
    id: "8",
    title: "Cosmic Journey",
    artist: "Stellar Sound",
    cover: "/photo.avif?height=200&width=200&text=Cosmic+Journey",
  },
  {
    id: "9",
    title: "Electric Soul",
    artist: "Voltage Vibes",
    cover: "/photo.avif?height=200&width=200&text=Electric+Soul",
  },
  {
    id: "10",
    title: "Quantum Beats",
    artist: "Particle Wave",
    cover: "/photo.avif?height=200&width=200&text=Quantum+Beats",
  },
  {
    id: "11",
    title: "Neon Dystopia",
    artist: "Cyber Punk",
    cover: "/photo.avif?height=200&width=200&text=Neon+Dystopia",
  },
  {
    id: "12",
    title: "Astral Projection",
    artist: "Cosmic Voyager",
    cover: "/photo.avif?height=200&width=200&text=Astral+Projection",
  },
]

export const songs = [
  {
    id: "1",
    title: "Electric Dreams",
    artist: "Neon Wave",
    album: "Synthwave Nights",
    duration: 237,
    albumCover: "/placeholder.svg?height=40&width=40&text=SW",
  },
  {
    id: "2",
    title: "Midnight Drive",
    artist: "Retrowave",
    album: "Neon City",
    duration: 198,
    albumCover: "/placeholder.svg?height=40&width=40&text=NC",
  },
  {
    id: "3",
    title: "Cyber Punk",
    artist: "Digital Assassin",
    album: "Future Shock",
    duration: 312,
    albumCover: "/placeholder.svg?height=40&width=40&text=FS",
  },
  {
    id: "4",
    title: "Neon Lights",
    artist: "Glow Riders",
    album: "Electric Avenue",
    duration: 245,
    albumCover: "/placeholder.svg?height=40&width=40&text=EA",
  },
  {
    id: "5",
    title: "Retro Future",
    artist: "Synth Lords",
    album: "Tomorrow's Yesterday",
    duration: 274,
    albumCover: "/placeholder.svg?height=40&width=40&text=TY",
  },
  {
    id: "6",
    title: "Digital Love",
    artist: "Pixel Heart",
    album: "8-Bit Romance",
    duration: 226,
    albumCover: "/placeholder.svg?height=40&width=40&text=8BR",
  },
  {
    id: "7",
    title: "Outrun",
    artist: "Sunset Cruisers",
    album: "Miami Nights",
    duration: 289,
    albumCover: "/placeholder.svg?height=40&width=40&text=MN",
  },
  {
    id: "8",
    title: "Laser Grid",
    artist: "Vector Graphics",
    album: "Digital Dreams",
    duration: 254,
    albumCover: "/placeholder.svg?height=40&width=40&text=DD",
  },
  {
    id: "9",
    title: "Cyber City",
    artist: "Neon Dystopia",
    album: "Future Shock",
    duration: 301,
    albumCover: "/placeholder.svg?height=40&width=40&text=FS",
  },
  {
    id: "10",
    title: "Analog Memories",
    artist: "Cassette Dreams",
    album: "Rewind",
    duration: 267,
    albumCover: "/placeholder.svg?height=40&width=40&text=RW",
  },
  {
    id: "11",
    title: "Virtual Reality",
    artist: "Digital Nomad",
    album: "Cyberspace",
    duration: 318,
    albumCover: "/placeholder.svg?height=40&width=40&text=CS",
  },
  {
    id: "12",
    title: "Hologram Heart",
    artist: "Pixel Emotion",
    album: "Digital Love",
    duration: 243,
    albumCover: "/placeholder.svg?height=40&width=40&text=DL",
  },
  {
    id: "13",
    title: "Arcade Dreams",
    artist: "8-Bit Heroes",
    album: "Game Over",
    duration: 231,
    albumCover: "/placeholder.svg?height=40&width=40&text=GO",
  },
  {
    id: "14",
    title: "Neon Sunset",
    artist: "Retrowave",
    album: "Neon City",
    duration: 285,
    albumCover: "/placeholder.svg?height=40&width=40&text=NC",
  },
  {
    id: "15",
    title: "Digital Horizon",
    artist: "Cyber Collective",
    album: "Future Shock",
    duration: 297,
    albumCover: "/placeholder.svg?height=40&width=40&text=FS",
  },
]
